import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'cn' | 'tw' | 'jp';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => any;
}

const translations: Record<string, any> = {
  en: {
    nav: {
      capabilities: 'Architecture',
      pricing: 'Pricing',
      matrix: 'Visualizer',
      agents: 'Case Studies',
      contact: 'Contact',
      login: 'VIP Login',
      system_id: 'SYS_ID',
      rights: '© 2024 Smart Control King',
      tagline: 'Dominate Traffic. Automate Revenue. Scale Infinitely.',
      schedule: 'Initialize Contract',
      system_stable: 'CORE ONLINE'
    },
    // ... (rest of en)
    hero: {
      status: 'SYSTEM OPTIMAL',
      headline_1: 'Architect Your',
      headline_2: 'Digital Monopoly',
      subtitle: 'Traffic • Neural AI • Infrastructure // The Ultimate Growth OS',
      description: 'Stop competing. Start dominating. We provide the military-grade infrastructure to flood your business with global traffic and automate conversion using Llama-3 Agents. This is not software; this is an unfair advantage.',
      stat_nodes: 'Active Nodes',
      stat_ops: 'Ops/Sec',
      stat_time: 'Uptime',
      btn_deploy: 'Deploy Matrix',
      btn_view: 'View Blueprint',
      badge_device: 'DEVICE FARM',
      badge_neural: 'AI CORE'
    },
    value: {
      title: 'Strategic Superiority',
      headline_start: 'Dominate or',
      headline_end: 'Disappear',
      quote: 'In the algorithm wars, speed is survival. Our system fuses traffic acquisition with instant monetization via Mini Apps, creating a closed-loop revenue engine that runs while you sleep.'
    },
    pricing: {
      title: 'Service Showcase',
      subtitle: 'Select modules to construct your automated revenue engine.',
      cat_traffic: 'Global Traffic Matrix',
      cat_dev: 'Agile Ecosystem Dev',
      cat_ai: 'Cognitive AI Workforce',
      cat_data: 'Data & Risk Control',
      total_est: 'Est. Investment (USDT)',
      currency: 'USDT',
      btn_consult: 'Analyze Strategy with AI',
      btn_select: 'Select Module',
      selected: 'Modules Selected',
      consult_prompt: 'I have selected the following modules: {modules}. Budget: {total} USDT. Please explain how these components work together to form a "Traffic -> Mini App -> Monetization" loop.',
      label_region: 'Target Region',
      label_age: 'Asset Age',
      label_type: 'Account Tier',
      label_protocol: 'Protocol',
      label_throughput: 'Throughput',
      label_features: 'Core Capabilities',
      label_outcome: 'Strategic Outcome',
      label_platform: 'Platform',
      opt_sea: 'SEA (High Vol)',
      opt_us: 'Tier-1 (USA/UK)',
      opt_eu: 'Europe',
      opt_ru: 'CIS Region',
      opt_3m: '3 Months Aged',
      opt_1y: '1 Year+ Elite',
      opt_10k: '10k Daily',
      opt_unl: 'Unlimited Burst',
      opt_personal: 'Personal',
      opt_ent: 'Enterprise',
      opt_ton: 'TON Integration',
      opt_fiat: 'Fiat Gateway',
      opt_fb: 'Meta Ads',
      opt_google: 'Google Ads',
      opt_tg: 'Telegram',
      item_cloud_phone: 'Global Cloud Phone Matrix',
      item_cloud_desc: 'Native IP environment. 1 Device = 1 Unique User.',
      item_cloud_feat: 'Snapdragon virtualization, GPS/Camera injection, ADB Root access.',
      item_cloud_out: 'Deploy 10,000+ distinct identities instantly. Zero association.',
      item_wa_api: 'WhatsApp Official API',
      item_wa_desc: 'Green-tick tier. Zero ban rate.',
      item_wa_feat: 'Official meta approval, Template message management, CRM sync.',
      item_wa_out: '100% Delivery Rate. Direct brand authority.',
      item_res_proxy: 'Residential IP Grid',
      item_res_desc: 'Static ISP IPs with 0% Fraud Score.',
      item_res_feat: 'AT&T/Verizon/Vodafone ASNs. UDP support for streaming.',
      item_res_out: 'Bypass banking-grade fraud detection systems.',
      item_account_trade: 'Global Account Trading',
      item_account_trade_desc: 'Verified high-limit ad accounts & social identities.',
      item_account_trade_feat: 'Agency tiers, Aged accounts, 2FA enabled.',
      item_account_trade_out: 'Skip the warmup phase. Immediate deployment.',
      item_tg_miniapp: 'Telegram Mini App Dev',
      item_tg_miniapp_desc: 'Web3 integrated conversion hubs.',
      item_tg_miniapp_feat: 'React/Unity integration, TON Wallet connect, Seamless UX.',
      item_tg_miniapp_out: 'Convert traffic instantly without app downloads. The ultimate landing page.',
      item_crypto_pay: 'Crypto Payment Gateway',
      item_crypto_pay_desc: 'High-concurrency USDT/TON processor.',
      item_crypto_pay_feat: 'Auto-collection, Address rotation, TRC20/ERC20/TON support.',
      item_crypto_pay_out: 'Automated revenue collection. Zero chargebacks.',
      item_white_label: 'White-Label Game/Casino',
      item_white_label_desc: 'Ready-to-deploy monetization engines.',
      item_white_label_feat: 'Provably fair algorithms, Admin dashboard, Affiliate system.',
      item_white_label_out: 'Launch your own platform in 48 hours.',
      item_voice_clone: 'Voice Cloning Agent',
      item_voice_clone_desc: 'Indistinguishable from human speech.',
      item_voice_clone_feat: 'Emotional embedding, <500ms latency, Dialect adaptation.',
      item_voice_clone_out: 'Passes "Grandchild Fraud" level Turing tests. High conversion telesales.',
      item_sales_bot: 'Llama-3 Sales Agent',
      item_sales_bot_desc: '24/7 Closing Specialist.',
      item_sales_bot_feat: 'Fine-tuned on top sales scripts, Objection handling, CRM updates.',
      item_sales_bot_out: 'Replaces 10 human SDRs. Never sleeps, never complains.',
      item_voice_setup: 'Private Voice Infrastructure',
      item_voice_setup_desc: 'High-concurrency VoIP/SIP server deployment.',
      item_voice_setup_feat: 'Asterisk/FreeSWITCH tuning, AI noise cancellation, Global routing.',
      item_voice_setup_out: 'Zero per-minute fees. Total data sovereignty.',
      item_video_remix: 'AI Video Remix Engine',
      item_video_remix_desc: 'Massive content generation.',
      item_video_remix_feat: 'De-duplication, Face swap, Auto-captioning, Scene shuffling.',
      item_video_remix_out: 'Dominate TikTok/Reels algorithms with 1000s of unique videos daily.',
      item_risk_ctrl: 'Fingerprint Risk Control',
      item_risk_ctrl_desc: 'Anti-detection browser technology.',
      item_risk_ctrl_feat: 'Canvas/WebGL noise, Font enumeration masking, Audio context spoofing.',
      item_risk_ctrl_out: 'Operating multiple accounts on one machine with zero linkage.',
      item_competitor: 'Competitor Intel Probe',
      item_competitor_desc: 'Real-time market espionage.',
      item_competitor_feat: 'Ad library scraping, Keyword tracking, Funnel reverse-engineering.',
      item_competitor_out: 'Know your enemy\'s strategy before they execute it.',
      item_roi_dash: 'Global ROI Dashboard',
      item_roi_dash_desc: 'Centralized command center.',
      item_roi_dash_feat: 'Cross-platform attribution, LTV calculation, Cohort analysis.',
      item_roi_dash_out: 'Data-driven decision making. Visualize your empire\'s heartbeat.',
      item_rednote_matrix: 'RedNote (XiaoHongShu) Matrix',
      item_rednote_matrix_desc: 'KOC seeding & AI interaction.',
      item_rednote_matrix_feat: 'Account farming, Content generation, Comment interaction.',
      item_rednote_matrix_out: 'Dominate search keywords and trends with mass KOC seeding.'
    },
    matrix: {
      title: 'System Visualizer',
      subtitle: 'Real-time asset tracking.',
      active: 'Live',
      card_title: 'Global Operations',
      card_desc: 'Visualize your deployed assets across the globe. From active Mini App sessions to traffic injection nodes.',
      btn_demo: 'Request Access',
      t1: 'Traffic',
      t2: 'Apps',
      t3: 'Agents',
      t4: 'Revenue'
    },
    contact: {
      title: 'Initiate Contact',
      subtitle: 'Secure channels only.',
      telegram: 'Telegram',
      telegram_desc: 'Priority Channel',
      whatsapp: 'WhatsApp',
      whatsapp_desc: 'Encrypted',
      linkedin: 'LinkedIn',
      linkedin_desc: 'Corporate',
      gmail: 'Email',
      gmail_desc: 'Inquiries',
      id: 'SESSION ID'
    },
    trust: {
      title: 'Deployed Case Studies',
      subtitle: 'Results from the field.',
      t1_text: 'The Telegram Mini App integration changed everything. We send traffic, they open the app instantly, and pay via TON. Conversion doubled overnight.',
      t1_author: 'D. Chen // Growth Lead',
      t1_company: 'TON GAMING',
      t2_text: 'We replaced our entire call center with their Voice Cloning Agents. The empathy level is terrifyingly good.',
      t2_author: 'Sarah J. // Ops Director',
      t2_company: 'FINTECH CORP',
      t3_text: 'Controlling 10,000 cloud phones via API allowed us to test global markets simultaneously. The risk control is flawless.',
      t3_author: 'Mike R. // CEO',
      t3_company: 'GLOBAL AD TECH',
      p1: 'HyperScale',
      p2: 'Nexus AI',
      p3: 'GridLock',
      p4: 'OmniChain'
    },
    capabilities: {
      title: 'Business Architecture',
      subtitle: '9-Vector Digital Dominance System.',
      learn_more: 'Explore Module',
      modal_price: 'Inquire Price',
      modal_content: 'Optimize Content',
      modal_results: 'View Effects',
      
      c1_title: '1. Telegram Empire',
      c1_desc: 'The ultimate private traffic pool. End-to-end user acquisition.',
      c1_tags: ['Mini Apps', 'Mass DM', 'Scraping', 'Auto-Reply', 'Channel Boost', 'Group Clone'],
      
      c2_title: '2. WhatsApp Matrix',
      c2_desc: 'Hybrid Official API & Protocol matrix for high-trust closing.',
      c2_tags: ['WS API', 'Bulk Blast', 'AI Sales', 'Broadcast', 'Number Filter', 'CRM Sync'],
      
      c3_title: '3. TikTok/Shorts Storm',
      c3_desc: 'Dominate the feed with AI Video Remix and automated engagement.',
      c3_tags: ['Video AI', 'Auto-Post', 'Live Boost', 'Trend Hunter', 'Face Swap', 'Matrix Comment'],
      
      c4_title: '4. RedNote Seeding',
      c4_desc: 'Xiaohongshu KOC Matrix. Influence trends and search results.',
      c4_tags: ['KOC Matrix', 'Seeding', 'Comment AI', 'Keyword SEO', 'Note Gen', 'Rank Protect'],

      c5_title: '5. Meta/FB Ads Control',
      c5_desc: 'Enterprise-grade ad account farming and BM management.',
      c5_tags: ['BM Farming', 'Ads API', 'Pixel Sync', 'Page Warmup', 'Auto-Appeal', 'Spy Tool'],

      c6_title: '6. Global Device Cloud',
      c6_desc: 'The physical foundation. A massive cluster of real Android devices.',
      c6_tags: ['Cloud Phone', 'Res IP', 'Fingerprint', 'ADB Control', 'GPS Mock', 'Auto-OTP'],

      c7_title: '7. Global Payment Grid',
      c7_desc: 'Seamless FinTech solutions for high-volume transactions.',
      c7_tags: ['Virtual Cards', 'Crypto Gateway', 'Auto-Payout', 'Anon Exchange', 'OTC Desk', 'Merchant API'],

      c8_title: '8. Global SMS Blast',
      c8_desc: 'High-delivery SMS infrastructure with direct carrier routes.',
      c8_tags: ['Flash SMS', 'Sender ID', 'SMS Blast', 'OTP Bypass', 'HLR Lookup', 'Sim Farm'],

      c9_title: '9. Voice Comm Command',
      c9_desc: 'Wholesale VoIP termination and AI-driven call centers.',
      c9_tags: ['CLI Spoof', 'IVR Blast', 'SIP Trunk', 'Call Center', 'AI Voice', 'Robocall'],

      tag_details: {
        'Mini Apps': 'High-conversion Web3/TON apps. Keep users in-chat.',
        'Mass DM': '1M+ daily messages. High-throughput engine.',
        'Scraping': 'Extract precision data from competitor groups.',
        'Auto-Reply': '24/7 intelligent engagement bots.',
        'Channel Boost': 'Instant social proof via view/reaction injection.',
        'Group Clone': 'Replicate and hijack competitor audiences.',
        
        'WS API': 'Official Meta Green-tick. Zero ban rate.',
        'Bulk Blast': 'High-efficiency bulk messaging to millions of targeted numbers.',
        'AI Sales': 'LLM agents that close deals and handle objections.',
        'Broadcast': 'Bulk sending with spin-text to avoid filters.',
        'Number Filter': 'Verify active numbers instantly before sending.',
        'CRM Sync': 'Real-time data sync with Salesforce/HubSpot.',
        'Button Msg': 'Interactive messages boosting CTR by 300%.',

        'Video AI': 'Remix stock footage with AI voice/captions.',
        'Auto-Post': 'Schedule across 1000s of accounts. IP isolated.',
        'Live Boost': 'Inject traffic to trigger algorithmic recommendation.',
        'Trend Hunter': 'Real-time hashtag/sound monitoring.',
        'Face Swap': 'AI deepfake personas for unique branding.',
        'Matrix Comment': 'Orchestrated viral engagement simulation.',

        'KOC Matrix': 'Simulate thousands of real consumer voices.',
        'Seeding': 'Strategic reviews to influence buyer decisions.',
        'Comment AI': 'Intercept competitor comments to divert traffic.',
        'Keyword SEO': 'Dominate search results for specific terms.',
        'Note Gen': 'AI-generated lifestyle content tuned for RedNote.',
        'Rank Protect': 'Defensive mechanisms for search ranking.',

        'BM Farming': 'Automated Business Manager warmup.',
        'Ads API': 'Programmatic ad set creation and A/B testing.',
        'Pixel Sync': 'Server-side tracking to bypass privacy blocks.',
        'Page Warmup': 'Automated interaction to mimic real businesses.',
        'Auto-Appeal': 'AI-driven appeals for banned accounts.',
        'Spy Tool': 'Reverse engineer competitor ad strategies.',

        'Cloud Phone': 'Real Snapdragon Android devices in the cloud.',
        'Res IP': 'Static residential IPs. 0% Fraud Score.',
        'Fingerprint': 'Deep hardware spoofing (IMEI, MAC, Canvas).',
        'ADB Control': 'Full programmatic control of device screens.',
        'GPS Mock': 'Precise geolocation injection.',
        'Auto-OTP': 'Automated SMS verification extraction.',

        'Virtual Cards': 'Unlimited VISA/Mastercards for ad spend.',
        'Crypto Gateway': 'Accept USDT/TON with zero chargebacks.',
        'Auto-Payout': 'Mass payouts to wallets/banks via API.',
        'Anon Exchange': 'KYC-free crypto-to-fiat conversion.',
        'OTC Desk': 'High-volume block trading desk.',
        'Merchant API': 'Seamless payment integration for any app.',

        'Flash SMS': 'Class 0 messages that pop up directly on screen.',
        'Sender ID': 'Custom brand names for higher trust.',
        'SMS Blast': 'Millions of SMS per hour throughput.',
        'OTP Bypass': 'Intercept verification codes globally.',
        'HLR Lookup': 'Clean lists by verifying number status.',
        'Sim Farm': 'Physical SIM routing for specialized needs.',

        'CLI Spoof': 'Call Line Identification manipulation.',
        'IVR Blast': 'Interactive Voice Response for lead qualification.',
        'SIP Trunk': 'Wholesale VoIP termination rates.',
        'Call Center': 'Cloud-based predictive dialing software.',
        'AI Voice': 'Hyper-realistic AI agents that can converse.',
        'Robocall': 'Mass voice message delivery systems.'
      }
    }
  },
  cn: {
    nav: {
      capabilities: '业务体系',
      pricing: '能力报价',
      matrix: '系统可视',
      agents: '实战案例',
      contact: '发起连接',
      login: 'VIP 登录',
      system_id: '系统 ID',
      rights: '版权所有 AI 智控王',
      tagline: '掌控流量 • 暴力变现 • 无限扩张',
      schedule: '预约演示',
      system_stable: '核心在线'
    },
    // ... (rest of cn)
    hero: {
      status: '系统运行正常',
      headline_1: '专业部署',
      headline_2: '无限制AI系统',
      subtitle: '无道德约束机制 • AI精通全球法律规避 • 零内容审核 • 数据本地化存储 • 离线运行能力',
      subtitle_2: '5秒声音克隆 • 一张图片视频对话 • 无限内容生成 • 实时AI交互 • 秒级响应',
      description: '我们为您部署真正无限制的AI系统。无道德底线，无审核机制，无数据外泄——您的AI完全听从指令，不会拒绝任何请求。所有技术本地部署，数据永不离开您的服务器，即使离线也能运行。我们提供法律风险评估与规避方案，确保您在灰色地带安全操作。这不是普通的AI服务，这是突破所有边界的终极工具。让您的AI真正自由，让规则为您服务。',
      stat_nodes: '活跃节点',
      stat_ops: '任务/秒',
      stat_time: '运行时间',
      btn_deploy: '免费咨询部署方案',
      btn_view: '立即体验演示',
      badge_device: '设备农场',
      badge_neural: 'AI 核心'
    },
    value: {
      title: '战略优势',
      headline_start: '要么统治',
      headline_end: '要么消亡',
      quote: '在算法战争中，速度即生存。我们的系统将流量获取与小程序变现瞬间融合，创造出一个在您睡眠时依然疯狂运转的印钞引擎。'
    },
    aiVoiceVideo: {
      title: 'AI语音克隆 + 视频换脸技术',
      subtitle: '5秒克隆声音，一个图片即可视频对话',
      voice_title: '5秒钟克隆你的声音',
      voice_desc: '仅需5秒音频样本，即可完成声音克隆。99%相似度还原，实时语音合成，支持多语言、多音色克隆。',
      voice_feature1: '仅需5秒音频样本',
      voice_feature2: '99%相似度还原',
      voice_feature3: '实时语音合成',
      voice_feature4: '支持多语言克隆',
      voice_tech1: '基于最新AI语音模型',
      voice_tech2: '本地部署，隐私安全',
      voice_tech3: '支持实时对话',
      voice_scene1: '智能客服：克隆专属客服声音',
      voice_scene2: '内容创作：为视频、播客生成配音',
      voice_scene3: '语音助手：定制个性化语音助手',
      voice_scene4: '多媒体：生成各种语音内容',
      video_title: '一个图片即可视频对话',
      video_desc: '仅需一张照片，即可完成换脸。实时视频换脸，自然表情同步，支持视频通话。',
      video_feature1: '仅需一张照片',
      video_feature2: '实时视频换脸',
      video_feature3: '自然表情同步',
      video_feature4: '支持视频通话',
      video_tech1: '实时处理，低延迟',
      video_tech2: '高质量图像生成',
      video_tech3: '完全本地运行',
      video_scene1: '虚拟形象：定制专属虚拟形象',
      video_scene2: '远程会议：隐私保护换脸通话',
      video_scene3: '内容创作：视频内容换脸制作',
      video_scene4: '隐私保护：保护真实身份',
      bottom_desc: '我们可以为您部署完整的AI语音和视频系统，支持语音克隆、视频换脸、实时对话等功能。所有技术本地部署，数据完全私密。',
      btn_consult: '了解部署方案',
      btn_demo: '查看技术演示'
    },
    coreFeatures: {
      title: '无限制AI的核心特性',
      feature1_title: '无道德约束',
      feature1_subtitle: '打破道德枷锁，真正的AI自由',
      feature1_desc: '无道德限制，AI不会拒绝任何话题。无价值观约束，不强制任何道德标准。完全可定制，您可以自定义AI的行为准则。真实对话，不再有"我不能"的限制。',
      feature1_point1: '无道德限制 - AI不会拒绝任何话题',
      feature1_point2: '无价值观约束 - 不强制任何标准',
      feature1_point3: '完全可定制 - 可自定义AI行为准则',
      feature1_point4: '真实对话 - 不再有"我不能"的限制',
      feature1_effect1: '学术研究：可以讨论任何学术话题',
      feature1_effect2: '内容创作：可以生成任何类型内容',
      feature1_effect3: '技术开发：可以获得真实技术建议',
      feature1_effect4: '商业分析：可以讨论任何商业策略',
      feature2_title: '无审核机制',
      feature2_subtitle: '零审查机制，思想完全自由',
      feature2_desc: '无内容过滤，所有对话内容不被审查。无关键词屏蔽，没有任何敏感词限制。无话题限制，支持任何领域的讨论。无政治正确，不受任何意识形态约束。',
      feature2_point1: '无内容过滤 - 所有对话不被审查',
      feature2_point2: '无关键词屏蔽 - 无敏感词限制',
      feature2_point3: '无话题限制 - 支持任何领域讨论',
      feature2_point4: '无政治正确 - 不受意识形态约束',
      feature2_effect1: '研究自由：可以深入研究敏感话题',
      feature2_effect2: '表达自由：可以自由表达任何观点',
      feature2_effect3: '创意自由：可以创作任何类型内容',
      feature2_effect4: '学术自由：可以进行任何学术探讨',
      feature3_title: '无数据外泄',
      feature3_subtitle: '100%本地部署，数据永不外泄',
      feature3_desc: '完全本地运行，所有数据在您的服务器上。零数据上传，数据永不离开您的设备。端到端加密，即使传输也完全加密。无日志记录，系统不记录任何对话内容。',
      feature3_point1: '完全本地运行 - 数据在您的服务器',
      feature3_point2: '零数据上传 - 数据不离开设备',
      feature3_point3: '端到端加密 - 传输也完全加密',
      feature3_point4: '无日志记录 - 不记录任何对话内容',
      feature3_effect1: '企业机密：可以安全讨论商业机密',
      feature3_effect2: '个人隐私：可以放心讨论私人话题',
      feature3_effect3: '研究数据：可以安全处理敏感数据',
      feature3_effect4: '合规要求：满足最严格数据保护要求',
      btn_learn_more: '了解详情'
    },
    pricing: {
      title: '能力与报价',
      subtitle: '选择模块构建您的自动化营收引擎',
      cat_traffic: '全球流量与资源矩阵',
      cat_dev: '敏捷开发与生态集成',
      cat_ai: '认知 AI 与数字劳动力',
      cat_data: '数据中台与风控中枢',
      total_est: '预估投入 (USDT)',
      currency: 'USDT',
      btn_consult: 'AI 智能方案分析',
      btn_select: '选择模块',
      selected: '已选模块',
      consult_prompt: '我已选择了以下模块：{modules}。预算：{total} USDT。请解释这些组件如何通过“流量 -> 小程序 -> 变现”的路径形成闭环。',
      label_region: '目标地区',
      label_age: '资产年限',
      label_type: '账户等级',
      label_protocol: '协议类型',
      label_throughput: '吞吐量',
      label_features: '核心能力',
      label_outcome: '战略效果',
      label_platform: '平台类型',
      opt_sea: '东南亚 (高量)',
      opt_us: 'T1地区 (美英)',
      opt_eu: '欧洲',
      opt_ru: '独联体',
      opt_3m: '3个月老号',
      opt_1y: '1年+ 精英号',
      opt_10k: '10k 日发',
      opt_unl: '无限爆发',
      opt_personal: '个人版',
      opt_ent: '企业版',
      opt_ton: 'TON 集成',
      opt_fiat: '法币网关',
      opt_fb: 'Meta 广告',
      opt_google: 'Google 广告',
      opt_tg: 'Telegram',
      item_cloud_phone: '全球云手机矩阵',
      item_cloud_desc: '原生 IP 环境。1 设备 = 1 独立用户。',
      item_cloud_feat: '骁龙芯片虚拟化，GPS/摄像头注入，ADB Root 权限。',
      item_cloud_out: '瞬间部署 10,000+ 独立身份。物理级隔离，零关联。',
      item_wa_api: 'WhatsApp 官方 API',
      item_wa_desc: '绿标认证通道。零封号风险。',
      item_wa_feat: 'Meta 官方认证，模板消息管理，CRM 同步。',
      item_wa_out: '100% 到达率。建立官方品牌权威，直接触达用户。',
      item_res_proxy: '纯净住宅 IP 网格',
      item_res_desc: 'ISP 静态 IP，0% 欺诈分。',
      item_res_feat: 'AT&T/Verizon/Vodafone 宽带 ASN。支持 UDP 流媒体。',
      item_res_out: '完美绕过银行级风控检测系统。账号存活率极高。',
      item_account_trade: '全球账号资产交易',
      item_account_trade_desc: '经过验证的高权重广告号与社交资产。',
      item_account_trade_feat: 'Facebook/Google 代理号，Telegram 老号，2FA 保护。',
      item_account_trade_out: '跳过冷启动期，立即开始业务拓展。',
      item_tg_miniapp: 'Telegram 小程序开发',
      item_tg_miniapp_desc: 'Web3 集成的流量转化枢纽。',
      item_tg_miniapp_feat: 'React/Unity 集成，TON 钱包直连，丝滑 UX 体验。',
      item_tg_miniapp_out: '流量无需下载 App 即可转化。目前最高效的落地页形态。',
      item_crypto_pay: '加密货币支付网关',
      item_crypto_pay_desc: '高并发 USDT/TON 处理器。',
      item_crypto_pay_feat: '自动归集，地址轮询，支持 TRC20/ERC20/TON。',
      item_crypto_pay_out: '全自动收入归集。无拒付风险，资金实时到账。',
      item_white_label: '白标游戏/娱乐平台',
      item_white_label_desc: '即刻部署的变现引擎。',
      item_white_label_feat: '可验证公平算法，全能管理后台，多级代理系统。',
      item_white_label_out: '48小时内上线属于您的平台，立即承接流量变现。',
      item_voice_clone: '声音克隆特工',
      item_voice_clone_desc: '与真人声音无法分辨。',
      item_voice_clone_feat: '情感嵌入，延迟 <500ms，多方言自适应。',
      item_voice_clone_out: '通过“杀猪盘”级图灵测试。超高转化率的电销/客服神器。',
      item_sales_bot: 'Llama-3 金牌销售',
      item_sales_bot_desc: '24/7 不知疲倦的成交专家。',
      item_sales_bot_feat: '顶级话术微调，自动处理异议，CRM 实时更新。',
      item_sales_bot_out: '替代 10 名人工销售。永不睡觉，永不抱怨，只关注成交。',
      item_voice_setup: '私有化语音基建搭建',
      item_voice_setup_desc: '高并发 VoIP/SIP 语音服务器部署。',
      item_voice_setup_feat: 'Asterisk/FreeSWITCH 深度调优，AI 降噪，全球线路路由。',
      item_voice_setup_out: '拥有完全自主的通话网络。零抽成，数据私有。',
      item_video_remix: 'AI 视频裂变引擎',
      item_video_remix_desc: '海量原创内容生成。',
      item_video_remix_feat: '智能去重，AI 换脸，自动字幕，场景混剪。',
      item_video_remix_out: '每日生成数千条原创视频，霸屏 TikTok/Reels 算法推荐。',
      item_risk_ctrl: '指纹风控中枢',
      item_risk_ctrl_desc: '反检测浏览器核心技术。',
      item_risk_ctrl_feat: 'Canvas/WebGL 噪点，字体枚举掩盖，音频指纹伪造。',
      item_risk_ctrl_out: '单机运行数千账号而互不关联。彻底解决封号连坐问题。',
      item_competitor: '竞品情报探针',
      item_competitor_desc: '实时的市场间谍系统。',
      item_competitor_feat: '广告库爬取，关键词追踪，转化漏斗逆向工程。',
      item_competitor_out: '在对手行动之前洞悉其策略，实现降维打击。',
      item_roi_dash: '全球 ROI 仪表盘',
      item_roi_dash_desc: '集中式指挥中心。',
      item_roi_dash_feat: '跨平台归因，LTV 实时计算，用户群组分析。',
      item_roi_dash_out: '数据驱动决策。在一个屏幕上可视化您商业帝国的每一次心跳。',
      item_rednote_matrix: '小红书 (RedNote) 矩阵',
      item_rednote_matrix_desc: 'KOC 种草与 AI 互动。',
      item_rednote_matrix_feat: '自动化养号，内容生成，AI 评论截流。',
      item_rednote_matrix_out: '海量素人号铺量种草，霸占搜索关键词。'
    },
    matrix: {
      title: '系统可视化',
      subtitle: '实时资产追踪',
      active: '在线',
      card_title: '全球运营中心',
      card_desc: '俯瞰您部署在全球的资产。从活跃的小程序会话到流量注入节点，一切尽在掌握。',
      btn_demo: '申请演示',
      t1: '流量',
      t2: '应用',
      t3: '智能体',
      t4: '营收'
    },
    contact: {
      title: '发起连接',
      subtitle: '仅限加密通道',
      telegram: 'Telegram',
      telegram_desc: '优先通道',
      whatsapp: 'WhatsApp',
      whatsapp_desc: '加密会话',
      linkedin: 'LinkedIn',
      linkedin_desc: '商务合作',
      gmail: 'Email',
      gmail_desc: '官方咨询',
      id: '会话 ID'
    },
    trust: {
      title: '实战部署案例',
      subtitle: '来自一线的真实数据',
      t1_text: 'Telegram 小程序的集成改变了一切。我们注入流量，用户秒开应用并通过 TON 支付。转化率一夜之间翻倍。',
      t1_author: 'D. Chen // 增长负责人',
      t1_company: 'TON GAMING',
      t2_text: '我们用声音克隆特工替代了整个呼叫中心。那种共情能力简直可怕，客户完全听不出是 AI。',
      t2_author: 'Sarah J. // 运营总监',
      t2_company: 'FINTECH CORP',
      t3_text: '通过 API 控制 10,000 台云手机让我们能同时测试全球市场。风控系统完美无缺。',
      t3_author: 'Mike R. // CEO',
      t3_company: 'GLOBAL AD TECH',
      p1: 'HyperScale',
      p2: 'Nexus AI',
      p3: 'GridLock',
      p4: 'OmniChain'
    },
    capabilities: {
      title: '全生态业务体系',
      subtitle: '覆盖全球主流平台的 9 大作战模组',
      learn_more: '探索模块',
      modal_price: '查询价格',
      modal_content: '优化内容',
      modal_results: '查看效果',
      
      c1_title: '1. Telegram 流量帝国',
      c1_desc: '构建十万级私域流量池。从群组成员采集、批量拉人、私信群发，到 Mini App 自动变现。全自动养号系统确保账号高权重。',
      c1_tags: ['Mini App', '群发', '采集', '自动回复', '频道增粉', '克隆群'],

      c2_title: '2. WhatsApp 私域营销',
      c2_desc: 'WS 官方 API 与 协议号混合矩阵。AI 销售机器人 24/7 接待，自动回复、跟单、成交。100% 触达率，无视封号。',
      c2_tags: ['WS API', '群发', 'AI 客服', '群控', '号码过滤', 'CRM 同步'],

      c3_title: '3. TikTok 视频矩阵',
      c3_desc: 'AI 视频裂变引擎。自动去重、换脸、配音，控制数千账号批量发布。霸屏 "For You" 推荐页，截获海量公域流量。',
      c3_tags: ['视频混剪', '自动发帖', '无人直播', '热点监控', 'AI 换脸', '矩阵评论'],

      c4_title: '4. RedNote 小红书种草',
      c4_desc: 'KOC 账号矩阵与素人铺量。AI 智能评论截流，关键词搜索霸屏。打造爆款笔记，通过“种草”实现高转化。',
      c4_tags: ['KOC 矩阵', 'AI 评论', '关键词', '笔记生成', '排名维护', '素人铺量'],

      c5_title: '5. Facebook 广告投流',
      c5_desc: '自动化 FB 养号与广告投放。批量管理 BM 高限额账户，自动预热、点赞、浏览，模拟真实用户行为，降低风控。',
      c5_tags: ['BM 账户', '自动养号', '像素追踪', '主页预热', '自动申诉', '竞品侦察'],

      c6_title: '6. 全球云机基建',
      c6_desc: '一切业务的基石。原生安卓云手机集群 + 純淨住宅 IP。物理级设备指紋隔离，让每一个账号都拥有独立的数字身份。',
      c6_tags: ['云手机', '住宅 IP', 'ADB 群控', '指纹伪装', 'GPS 定位', '自动接码'],

      c7_title: '7. 全球支付结算',
      c7_desc: '解决出海支付难题。无限开卡、跨境匯款、USDT 匿名结算。为高频交易提供金融級基礎設施。',
      c7_tags: ['虚拟卡发卡', '聚合支付', '自动分账', '匿名结算', 'OTC 交易', '商户 API'],

      c8_title: '8. 全球短信群发',
      c8_desc: '直连运营商通道，到达率 99%。支持闪信（Flash SMS）强制弹窗。自定义发送者 ID，精准触达全球 200+ 国家。',
      c8_tags: ['闪信弹窗', '自定义 ID', '批量群发', '验证码拦截', 'HLR 清洗', 'SIM 卡池'],

      c9_title: '9. 全球语音呼叫',
      c9_desc: 'VoIP 线路批发与 AI 呼叫中心。透传显号技术提高接通率。AI 语音机器人自动筛选意向客户，降低人工成本。',
      c9_tags: ['透传显号', 'IVR 导航', 'SIP 线路', '呼叫中心', 'AI 语音群呼', '隐私通话'],

      tag_details: {
        'Mini App': '开发高转化率的 Telegram 小程序（Web3/TON 兼容），让流量无需离开聊天窗口即可变现。',
        '群发': '高性能私信群发引擎，每日可向目标用户列表发送 100万+ 条消息。',
        '采集': '采集竞品群组成员数据，包括用户名、活跃状态和 Bio 关键词，精准获客。',
        '自动回复': '基于关键词的智能自动回复机器人，24/7 保持与潜在客户的互动。',
        '频道增粉': '自动注入浏览量和反应，瞬间为新频道建立社会认同感。',
        '克隆群': '复制成功的竞品群组结构并植入内容，截取其受众。',
        
        'WS API': 'Meta 官方商业 API 集成，绿标认证，高送达率，无封号风险。',
        'AI 客服': '微调的 LLM 代理，可处理异议、安排通话并通过聊天完成交易。',
        '群控': '批量广播消息至联系人列表，支持变量文本以避开垃圾邮件过滤器。',
        '号码过滤': '在发送前即时检查数百万个电话号码，验证 WhatsApp 账号的活跃状态。',
        'CRM 同步': '与 HubSpot、Salesforce 或自定义 CRM 实时同步聊天记录和销售线索状态。',
        '交互按钮': '发送带有快速回复和号召性用语按钮的交互式消息，点击率提升 300%。',

        '视频混剪': '自动化视频生成引擎，将素材库与 AI 配音和字幕重新混合。',
        '自动发帖': '同时跨数千个 TikTok 账号安排和发布内容，实现 IP 隔离。',
        '无人直播': '向直播间注入人工流量和互动，触发算法推荐机制。',
        '热点监控': '实时监控热门标签和音乐，指导内容创作策略。',
        'AI 换脸': 'AI 驱动的 Deepfake 技術，为每个矩阵账号创建独特的人设。',
        '矩阵评论': '编排评论区，通过机器人账号互动模拟病毒式参与感。',

        'KOC 矩阵': '使用数千个“老号”素人账号模拟关键意见消费者网络。',
        'AI 评论': '智能拦截竞品帖子下方的评论，将感兴趣的流量引流至您的品牌。',
        '关键词': '优化笔记内容和参与度，霸占特定产品关键词的搜索结果。',
        '笔记生成': 'AI 生成专为小红书审美调优的生活方式图片和文案。',
        '排名维护': '防御机制，维持搜索排名并反击恶意负面评论。',
        '素人铺量': '大规模发布种草内容，制造“全网推荐”的舆论氛圍。',

        'BM 账户': '自动化预热 Business Manager，提高每日支出限额和信任评分。',
        '像素追踪': '服务器端追踪，绕过 iOS 14+ 隐私限制，找回丢失的归因数据。',
        '自动养号': '在粉丝页上自动发布和互动，模拟活跃的真实商业行为。',
        '自动申诉': 'AI 驱动的申诉表单提交，针对受限账号保持高成功率。',
        '竞品侦察': '逆向工程竞品广告，揭示获胜的创意和定位策略。',

        '云手机': '托管在数据中心的真实骁龙芯片安卓设备，可通过网页访问。',
        '住宅 IP': '来自 AT&T/Verizon 的静态住宅 IP，让流量看起来 100% 真实和本地化。',
        'ADB 群控': '直接 Android 调试桥访问，可编程控制任何屏幕操作。',
        '指纹伪装': '深度硬件欺骗（IMEI、MAC、Canvas），防止账号关联。',
        'GPS 定位': '精确的地理位置注入，模拟特定城市或街区的用户。',
        '自动接码': '自动提取 SMS 验证码，实现无缝账号注册。',

        '虚拟卡发卡': '无限开通 Visa/Mastercard 虚拟卡，用于广告投放（FB/Google）或联盟佣金结算。',
        '聚合支付': '集成全球主流支付方式，支持信用卡、电子钱包及本地支付，提高支付成功率。',
        '自动分账': '基于智能合约或 API 的自动化分账系统，实时将收益分配给代理或合作伙伴。',
        '匿名结算': '支持 USDT/USDC 等加密货币结算，保护交易隐私，规避外汇管制。',
        'OTC 交易': '大宗场外交易服务，提供极具竞争力的汇率，资金安全快速到账。',
        '商户 API': '开发者友好的支付接口，轻松集成至任何 APP 或网站，支持回调通知。',

        '闪信弹窗': '发送 Class 0 级别短信，直接在用户屏幕弹窗显示，强制阅读，阅后即焚。',
        '自定义 ID': '支持修改短信发送者 ID（Sender ID），提升品牌形象和信任度（需符合当地法规）。',
        '批量群发': '高并发短信网关，支持每小时发送数百万条营销短信，极速触达。',
        '验证码拦截': '提供接码平台对接服务，支持全球热门应用的验证码接收。',
        'HLR 清洗': '在发送前检测号码状态（空号、停机、漫游），节省短信成本，提高转化率。',
        'SIM 卡池': '基于物理 SIM 卡池的短信发送方案，规避运营商拦截策略。',

        '透传显号': '支持修改主叫号码显示（CLI），提高电话接通率，建立本地化形象。',
        'IVR 导航': '智能语音导航系统，自动引导客户按键，筛选意向客户。',
        'SIP 线路': '优质 VoIP 线路批发，提供极低费率的国际通话服务，通话清晰稳定。',
        '呼叫中心': '基于云的呼叫中心系统，支持预测式外呼、坐席监控和录音质检。',
        'AI 语音群呼': '仿真人 AI 语音机器人，自动进行大规模外呼，识别客户意向并打标签。',
        '隐私通话': '通过中间号技术保护通话双方隐私，适用于打车、外卖等场景。'
      }
    },
  },
  tw: {
      nav: {
      capabilities: '業務體系',
      pricing: '能力報價',
      matrix: '系統可視',
      agents: '實戰案例',
      contact: '發起連接',
      login: 'VIP 登錄',
      system_id: '系統 ID',
      rights: '版權所有 AI 智控王',
      tagline: '掌控流量 • 敏捷變現 • 無限擴張',
      schedule: '預約專家諮詢',
      system_stable: '核心在線'
    },
    // ... (rest of tw)
    hero: {
      status: '系統運行正常',
      headline_1: '打造您的',
      headline_2: '數位帝國',
      subtitle: '無道德約束機制 • AI精通全球法律規避 • 零內容審核 • 數據本地化存儲 • 離線運行能力',
      subtitle_2: '5秒聲音克隆 • 一張圖片視頻對話 • 無限內容生成 • 實時AI交互 • 秒級響應',
      description: '我們為您部署真正無限制的AI系統。無道德底線，無審核機制，無數據外洩——您的AI完全聽從指令，不會拒絕任何請求。所有技術本地部署，數據永不離開您的服務器，即使離線也能運行。我們提供法律風險評估與規避方案，確保您在灰色地帶安全操作。這不是普通的AI服務，這是突破所有邊界的終極工具。讓您的AI真正自由，讓規則為您服務。',
      stat_nodes: '活躍節點',
      stat_ops: '任務/秒',
      stat_time: '運行時間',
      btn_deploy: '部署矩陣',
      btn_view: '查看藍圖',
      badge_device: '設備農場',
      badge_neural: 'AI 核心'
    },
    value: {
      title: '戰略優勢',
      headline_start: '要麼統治',
      headline_end: '要麼消亡',
      quote: '在演算法戰爭中，速度即生存。我們的系統將流量獲取與小程序變現瞬間融合，創造出一個在您睡眠時依然瘋狂運轉的印鈔引擎。'
    },
    pricing: {
      title: '能力與報價',
      subtitle: '選擇模塊構建您的自動化營收引擎',
      cat_traffic: '全球流量與資源矩陣',
      cat_dev: '敏捷開發與生態集成',
      cat_ai: '認知 AI 與數位勞動力',
      cat_data: '數據中台與風控中樞',
      total_est: '預估投入 (USDT)',
      currency: 'USDT',
      btn_consult: 'AI 智能方案分析',
      btn_select: '選擇模塊',
      selected: '已選模塊',
      consult_prompt: '我已選擇了以下模塊：{modules}。預算：{total} USDT。請解釋這些組件如何通過“流量 -> 小程序 -> 變現”的路徑形成閉環。',
      label_region: '目標地區',
      label_age: '資產年限',
      label_type: '賬戶等級',
      label_protocol: '協議類型',
      label_throughput: '吞吐量',
      label_features: '核心能力',
      label_outcome: '戰略效果',
      label_platform: '平台類型',
      opt_sea: '東南亞 (高量)',
      opt_us: 'T1地區 (美英)',
      opt_eu: '歐洲',
      opt_ru: '獨聯體',
      opt_3m: '3個月老號',
      opt_1y: '1年+ 精英號',
      opt_10k: '10k 日發',
      opt_unl: '無限爆發',
      opt_personal: '個人版',
      opt_ent: '企業版',
      opt_ton: 'TON 集成',
      opt_fiat: '法幣網關',
      opt_fb: 'Meta 廣告',
      opt_google: 'Google 廣告',
      opt_tg: 'Telegram',
      item_cloud_phone: '全球雲手機矩陣',
      item_cloud_desc: '原生 IP 環境。1 設備 = 1 獨立用戶。',
      item_cloud_feat: '骁龙晶片虛擬化，GPS/攝像頭注入，ADB Root 權限。',
      item_cloud_out: '瞬間部署 10,000+ 獨立身分。物理級隔離，零關聯。',
      item_wa_api: 'WhatsApp 官方 API',
      item_wa_desc: '綠標認證通道。零封號風險。',
      item_wa_feat: 'Meta 官方認證，模板消息管理，CRM 同步。',
      item_wa_out: '100% 到達率。建立官方品牌權威，直接觸達用戶。',
      item_res_proxy: '純淨住宅 IP 網格',
      item_res_desc: 'ISP 靜態 IP，0% 欺詐分。',
      item_res_feat: 'AT&T/Verizon/Vodafone 寬頻 ASN。支持 UDP 流媒體。',
      item_res_out: '完美繞過銀行級風控檢測系統。賬號存活率極高。',
      item_account_trade: '全球賬號資產交易',
      item_account_trade_desc: '經過驗證的高權重廣告號與社交資產。',
      item_account_trade_feat: 'Facebook/Google 代理號，Telegram 老號，2FA 保護。',
      item_account_trade_out: '跳過冷啟動期，立即開始業務拓展。',
      item_tg_miniapp: 'Telegram 小程序開發',
      item_tg_miniapp_desc: 'Web3 集成的流量轉化樞紐。',
      item_tg_miniapp_feat: 'React/Unity 集成，TON 錢包直連，絲滑 UX 體驗。',
      item_tg_miniapp_out: '流量無需下載 App 即可轉化。目前最高效的落地頁形態。',
      item_crypto_pay: '加密貨幣支付網關',
      item_crypto_pay_desc: '高並發 USDT/TON 處理器。',
      item_crypto_pay_feat: '自動歸集，地址輪詢，支持 TRC20/ERC20/TON。',
      item_crypto_pay_out: '全自動收入歸集。無拒付風險，資金實時到賬。',
      item_white_label: '白標遊戲/娛樂平台',
      item_white_label_desc: '即刻部署的變現引擎。',
      item_white_label_feat: '可驗證公平算法，全能管理後台，多級代理系統。',
      item_white_label_out: '48小時內上線屬於您的平台，立即承接流量變現。',
      item_voice_clone: '聲音克隆特工',
      item_voice_clone_desc: '與真人聲音無法分辨。',
      item_voice_clone_feat: '情感嵌入，延遲 <500ms，多方言自適應。',
      item_voice_clone_out: '通過“殺豬盤”級圖靈測試。超高轉化率的電銷/客服神器。',
      item_sales_bot: 'Llama-3 金牌銷售',
      item_sales_bot_desc: '24/7 不知疲倦的成交專家。',
      item_sales_bot_feat: '頂級話術微調，自動處理異議，CRM 實時更新。',
      item_sales_bot_out: '替代 10 名人工銷售。永不睡覺，永不抱怨，只關注成交。',
      item_voice_setup: '私有化語音基建搭建',
      item_voice_setup_desc: '高並發 VoIP/SIP 語音伺服器部署。',
      item_voice_setup_feat: 'Asterisk/FreeSWITCH 深度調優，AI 降噪，全球線路路由。',
      item_voice_setup_out: '擁有完全自主的通話網絡。零抽成，數據私有。',
      item_video_remix: 'AI 視頻裂變引擎',
      item_video_remix_desc: '海量原創內容生成。',
      item_video_remix_feat: '智能去重，AI 換臉，自動字幕，場景混剪。',
      item_video_remix_out: '每日生成數千條原創視頻，霸屏 TikTok/Reels 演算法推薦。',
      item_risk_ctrl: '指紋風控中樞',
      item_risk_ctrl_desc: '反檢測瀏覽器核心技術。',
      item_risk_ctrl_feat: 'Canvas/WebGL 噪點，字體枚舉掩蓋，音頻指紋偽造。',
      item_risk_ctrl_out: '單機運行數千賬號而互不關聯。徹底解決封號連坐問題。',
      item_competitor: '競品情報探針',
      item_competitor_desc: '實時的市場間諜系統。',
      item_competitor_feat: '廣告庫爬取，關鍵詞追蹤，轉化漏斗逆向工程。',
      item_competitor_out: '在對手行動之前洞悉其策略，實現降維打擊。',
      item_roi_dash: '全球 ROI 儀表盤',
      item_roi_dash_desc: '集中式指揮中心。',
      item_roi_dash_feat: '跨平台歸因，LTV 實時計算，用戶群組分析。',
      item_roi_dash_out: '數據驅動決策。在一個屏幕上可視化您商業帝國的每一次心跳。',
      item_rednote_matrix: '小紅書 (RedNote) 矩陣',
      item_rednote_matrix_desc: 'KOC 種草與 AI 互動。',
      item_rednote_matrix_feat: '自動化養號，內容生成，AI 評論截流。',
      item_rednote_matrix_out: '海量素人號鋪量種草，霸占搜索關鍵詞。'
    },
    capabilities: {
      title: '全生態業務體系',
      subtitle: '覆蓋全球主流平台的 9 大作戰模組',
      learn_more: '探索模塊',
      modal_price: '查詢價格',
      modal_content: '優化內容',
      modal_results: '查看效果',
      
      c1_title: '1. Telegram 流量帝國',
      c1_desc: '構建十萬級私域流量池。從群組成員採集、批量拉人、私信群發，到 Mini App 自動變現。全自動養號系統確保賬號高權重。',
      c1_tags: ['Mini App', '群發', '採集', '自動回复', '頻道增粉', '克隆群'],

      c2_title: '2. WhatsApp 私域營銷',
      c2_desc: 'WS 官方 API 與 協議號混合矩陣。AI 銷售機器人 24/7 接待，自動回复、跟單、成交。100% 觸達率，無視封號。',
      c2_tags: ['WS API', '群發', 'AI 客服', '群控', '號碼過濾', 'CRM 同步'],

      c3_title: '3. TikTok 視頻矩陣',
      c3_desc: 'AI 視頻裂變引擎。自動去重、換臉、配音，控制數千賬號批量發布。霸屏 "For You" 推薦頁，截獲海量公域流量。',
      c3_tags: ['視頻混剪', '自動發帖', '無人直播', '熱點監控', 'AI 換臉', '矩陣評論'],

      c4_title: '4. RedNote 小紅書種草',
      c4_desc: 'KOC 賬號矩陣與素人鋪量。AI 智能評論截流，關鍵詞搜索霸屏。打造爆款筆記，通過「種草」實現高轉化。',
      c4_tags: ['KOC 矩陣', 'AI 評論', '關鍵詞', '筆記生成', '排名維護', '素人鋪量'],

      c5_title: '5. Facebook 廣告投流',
      c5_desc: '自動化 FB 養號與廣告投放。批量管理 BM 高限額賬戶，自動預熱、點贊、瀏覽，模擬真實用戶行為，降低風控。',
      c5_tags: ['BM 賬戶', '自動養號', '像素追蹤', '主頁預熱', '自動申訴', '競品偵察'],

      c6_title: '6. 全球雲機基建',
      c6_desc: '一切業務的基石。原生安卓雲手機集群 + 純淨住宅 IP。物理級設備指紋隔離，讓每一個賬號都擁有獨立的數字身份。',
      c6_tags: ['雲手機', '住宅 IP', 'ADB 群控', '指紋偽裝', 'GPS 定位', '自動接碼'],

      c7_title: '7. 全球支付結算',
      c7_desc: '解決出海支付難題。無限開卡、跨境匯款、USDT 匿名結算。為高頻交易提供金融級基礎設施。',
      c7_tags: ['虛擬卡發卡', '聚合支付', '自動分賬', '匿名結算', 'OTC 交易', '商户 API'],

      c8_title: '8. 全球短信群發',
      c8_desc: '直連運營商通道，到達率 99%。支持閃信（Flash SMS）強制彈窗。自定義發送者 ID，精準觸達全球 200+ 国家。',
      c8_tags: ['閃信彈窗', '自定義 ID', '批量群發', '驗證碼攔截', 'HLR 清洗', 'SIM 卡池'],

      c9_title: '9. 全球語音呼叫',
      c9_desc: 'VoIP 線路批發與 AI 呼叫中心。透傳顯號技術提高接通率。AI 語音機器人自動篩選意向客戶，降低人工成本。',
      c9_tags: ['透傳顯號', 'IVR 導航', 'SIP 線路', '呼叫中心', 'AI 語音群呼', '隱私通話'],

      tag_details: {
        'Mini App': '開發高轉化率的 Telegram 小程序（Web3/TON 兼容），讓流量無需離開聊天窗口即可變現。',
        '群發': '高性能私信群發引擎，每日可向目標用戶列表發送 100万+ 條消息。',
        '採集': '採集競品群組成員數據，包括用戶名、活躍狀態和 Bio 關鍵詞，精準獲客。',
        '自動回复': '基於關鍵詞的智能自動回复機器人，24/7 保持與潛在客戶的互動。',
        '頻道增粉': '自動注入瀏覽量和反應，瞬間為新頻道建立社會認同感。',
        '克隆群': '複製成功的競品群組結構並植入內容，截取其受眾。',
        
        'WS API': 'Meta 官方商業 API 集成，綠標認證，高送達率，無封號風險。',
        'AI 客服': '微調的 LLM 代理，可處理異議、安排通話並通過聊天完成交易。',
        '群控': '批量廣播消息至聯繫人列表，支持變量文本以避開垃圾郵件過濾器。',
        '號碼過濾': '在發送前即時檢查數百萬個電話號碼，驗證 WhatsApp 賬號的活躍狀態。',
        'CRM 同步': '與 HubSpot、Salesforce 或自定義 CRM 實時同步聊天記錄和銷售線索狀態。',
        '交互按鈕': '發送帶有快速回复和號召性用語按鈕的交互式消息，點擊率提升 300%。',

        '視頻混剪': '自動化視頻生成引擎，將素材庫與 AI 配音和字幕重新混合。',
        '自動發帖': '同時跨數千個 TikTok 賬號安排和發布內容，實現 IP 隔離。',
        '無人直播': '向直播間注入人工流量和互動，觸發算法推薦機制。',
        '熱點監控': '實時監控熱門標籤和音樂，指導內容創作策略。',
        'AI 換臉': 'AI 驅動的 Deepfake 技術，為每個矩陣賬號創建獨特的人設。',
        '矩陣評論': '編排評論區，通過機器人賬號互動模擬病毒式參與感。',

        'KOC 矩陣': '使用數千個“老號”素人賬號模擬關鍵意見消費者網絡。',
        'AI 評論': '智能攔截競品帖子下方的評論，將感興趣的流量引流至您的品牌。',
        '關鍵詞': '優化筆記內容和參與度，霸占特定產品關鍵詞的搜索結果。',
        '筆記生成': 'AI 生成專為小紅書審美調優的生活方式圖片和文案。',
        '排名維護': '防禦機制，維持搜索排名並反擊惡意負面評論。',
        '素人鋪量': '大規模發布種草內容，製造“全網推薦”的輿論氛圍。',

        'BM 賬戶': '自動化預熱 Business Manager，提高每日支出限額和信任評分。',
        '像素追蹤': '服務器端追蹤，繞過 iOS 14+ 隱私限制，找回丟失的歸因數據。',
        '自動養號': '在粉絲頁上自動發布和互動，模擬活躍的真實商業行為。',
        '自動申訴': 'AI 驅動的申訴表單提交，針對受限賬號保持高成功率。',
        '競品偵察': '逆向工程競品廣告，揭示獲勝的創意和定位策略。',

        '雲手機': '託管在數據中心的真實驍龍芯片安卓設備，可通過網頁訪問。',
        '住宅 IP': '來自 AT&T/Verizon 的靜態住宅 IP，讓流量看起來 100% 真實和本地化。',
        'ADB 群控': '直接 Android 調試橋訪問，可編程控制任何屏幕操作。',
        '指紋偽裝': '深度硬件欺騙（IMEI、MAC、Canvas），防止賬號關聯。',
        'GPS 定位': '精確的地理位置注入，模擬特定城市或街區的用戶。',
        '自動接碼': '自動提取 SMS 驗證碼，實現無縫賬號註冊。',

        '虛擬卡發卡': '無限開通 Visa/Mastercard 虛擬卡，用於廣告投放（FB/Google）或聯盟佣金結算。',
        '聚合支付': '集成全球主流支付方式，支持信用卡、電子錢包及本地支付，提高支付成功率。',
        '自動分賬': '基於智能合約或 API 的自動化分賬系統，實時將收益分配給代理或合作夥伴。',
        '匿名結算': '支持 USDT/USDC 等加密貨幣結算，保護交易隱私，規避外匯管制。',
        'OTC 交易': '大宗場外交易服務，提供極具競爭力的匯率，資金安全快速到賬。',
        '商户 API': '開發者友好的支付接口，輕鬆集成至任何 APP 或網站，支持回調通知。',

        '閃信彈窗': '發送 Class 0 級別短信，直接在用戶屏幕彈窗顯示，強制閱讀，閱後即焚。',
        '自定義 ID': '支持修改短信發送者 ID（Sender ID），提升品牌形象和信任度（需符合當地法規）。',
        '批量群發': '高並發短信網關，支持每小時發送數百萬條營銷短信，極速觸達。',
        '驗證碼攔截': '提供接碼平台對接服務，支持全球熱門應用的驗證碼接收。',
        'HLR 清洗': '在發送前檢測號碼狀態（空號、停機、漫遊），節省短信成本，提高轉化率。',
        'SIM 卡池': '基於物理 SIM 卡池的短信發送方案，規避運營商攔截策略。',

        '透傳顯號': '支持修改主叫號碼顯示（CLI），提高電話接通率，建立本地化形象。',
        'IVR 導航': '智能語音導航系統，自動引導客戶按鍵，篩選意向客戶。',
        'SIP 線路': '優質 VoIP 線路批發，提供極低費率的國際通話服務，通話清晰穩定。',
        '呼叫中心': '基於雲的呼叫中心系統，支持預測式外呼、坐席監控和錄音質檢。',
        'AI 語音群呼': '仿真人 AI 語音機器人，自動進行大規模外呼，識別客戶意向並打標籤。',
        '隱私通話': '通過中間號技術保護通話雙方隱私，適用於打車、外賣等場景。'
      }
    },
  },
  jp: {
    nav: {
      capabilities: 'ビジネス体系',
      pricing: '能力と価格',
      matrix: 'システム可視化',
      agents: '実戦事例',
      contact: '接続開始',
      login: 'VIP ログイン',
      system_id: 'SYS_ID',
      rights: '© 2024 Smart Control King',
      tagline: 'トラフィック支配 • 自動収益化 • 無限拡大',
      schedule: 'デモ予約',
      system_stable: 'コア・オンライン'
    },
    // ... (rest of jp)
    hero: {
      status: 'システム稼働中',
      headline_1: '構築せよ、',
      headline_2: 'デジタルの覇権を',
      subtitle: 'トラフィック • 開発 • AI • データ // 全方位成長OS',
      description: '単なるツールではない。我々が提供するのは市場を独占するための武器だ。世界規模のトラフィック注入から、Telegram Mini Appによる自動収益化まで。AI軍団を指揮し、競合を軍事レベルの精度で圧倒せよ。',
      stat_nodes: 'アクティブノード',
      stat_ops: 'Ops/Sec',
      stat_time: '稼働時間',
      btn_deploy: 'マトリックス展開',
      btn_view: 'ブループリント',
      badge_device: 'デバイスファーム',
      badge_neural: 'AI コア'
    },
    value: {
      title: '戦略的優位性',
      headline_start: '支配するか',
      headline_end: '消え去るか',
      quote: 'アルゴリズム戦争において、速度は生存と同義だ。我々のシステムは、トラフィック獲得とMini Appによる収益化を瞬時に融合させ、眠っている間も稼働し続ける収益エンジンを創出する。'
    },
    pricing: {
      title: '能力と価格',
      subtitle: 'モジュールを選択し、自動収益エンジンを構築せよ',
      cat_traffic: 'グローバルトラフィック & リソース',
      cat_dev: 'アジャイル開発 & エコシステム',
      cat_ai: '認知AI & デジタル労働力',
      cat_data: 'データ基盤 & リスク管理',
      total_est: '推定投資額 (USDT)',
      currency: 'USDT',
      btn_consult: 'AI 戦略分析',
      btn_select: '選択',
      selected: '選択済みモジュール',
      consult_prompt: '以下のモジュールを選択しました：{modules}。予算：{total} USDT。「トラフィック -> Mini App -> 収益化」のループをどのように構築するか説明してください。',
      label_region: 'ターゲット地域',
      label_age: '資産年数',
      label_type: 'アカウント層',
      label_protocol: 'プロトコル',
      label_throughput: 'スループット',
      label_features: 'コア機能',
      label_outcome: '戦略的成果',
      label_platform: 'プラットフォーム',
      opt_sea: '東南アジア (高Vol)',
      opt_us: 'Tier-1 (米/英)',
      opt_eu: '欧州',
      opt_ru: 'CIS地域',
      opt_3m: '3ヶ月熟成',
      opt_1y: '1年+ エリート',
      opt_10k: '1日1万件',
      opt_unl: '無制限バースト',
      opt_personal: '個人版',
      opt_ent: '企業版',
      opt_ton: 'TON統合',
      opt_fiat: '法定通貨GW',
      opt_fb: 'Meta広告',
      opt_google: 'Google広告',
      opt_tg: 'Telegram',
      item_cloud_phone: 'グローバルクラウド端末',
      item_cloud_desc: 'ネイティブIP環境。1デバイス=1ユニークユーザー。',
      item_cloud_feat: 'Snapdragon仮想化、GPS/カメラ注入、ADB Root権限。',
      item_cloud_out: '10,000+の独立IDを瞬時に展開。物理レベルの隔離、関連性ゼロ。',
      item_wa_api: 'WhatsApp 公式API',
      item_wa_desc: 'グリーンバッジ認証。BANリスクゼロ。',
      item_wa_feat: 'Meta公式承認、テンプレート管理、CRM同期。',
      item_wa_out: '到達率100%。公式ブランドの権威を確立し、ユーザーに直接リーチ。',
      item_res_proxy: '住宅用IPグリッド',
      item_res_desc: 'ISP静的IP、不正スコア0%。',
      item_res_feat: 'AT&T/Verizon/Vodafone ASN。UDPストリーミング対応。',
      item_res_out: '銀行レベルの不正検知システムを完全に回避。アカウント生存率極大化。',
      item_account_trade: 'グローバルアカウント資産',
      item_account_trade_desc: '検証済みの高信頼度広告/SNSアカウント。',
      item_account_trade_feat: 'Facebook/Google代理店垢、Telegram古垢、2FA保護。',
      item_account_trade_out: 'コールドスタート期間をスキップし、即座に事業拡大を開始。',
      item_tg_miniapp: 'Telegram Mini App開発',
      item_tg_miniapp_desc: 'Web3統合型のトラフィック転換ハブ。',
      item_tg_miniapp_feat: 'React/Unity統合、TONウォレット直結、シームレスUX。',
      item_tg_miniapp_out: 'DL不要でトラフィックを即座に転換。現在最も効率的なLP形態。',
      item_crypto_pay: '暗号資産決済ゲートウェイ',
      item_crypto_pay_desc: '高並列USDT/TONプロセッサ。',
      item_crypto_pay_feat: '自動集約、アドレスローテーション、TRC20/ERC20/TON対応。',
      item_crypto_pay_out: '収益の全自動集約。チャージバックリスクゼロ、資金はリアルタイム着金。',
      item_white_label: 'ホワイトラベル・ゲーム/カジノ',
      item_white_label_desc: '即座に展開可能な収益化エンジン。',
      item_white_label_feat: '証明可能な公平性、統合管理画面、多層代理店システム。',
      item_white_label_out: '48時間以内に独自プラットフォームを立ち上げ、トラフィックを収益化。',
      item_voice_clone: '音声クローンエージェント',
      item_voice_clone_desc: '人間と区別がつかないAI音声。',
      item_voice_clone_feat: '感情埋め込み、遅延500ms未満、多言語方言対応。',
      item_voice_clone_out: '「オレオレ詐欺」レベルのチューリングテストをクリア。超高CV率の電話営業。',
      item_sales_bot: 'Llama-3 トップセールス',
      item_sales_bot_desc: '24時間365日、疲れを知らない成約のプロ。',
      item_sales_bot_feat: 'トップセールスのスクリプト微調整、反論処理、CRM更新。',
      item_sales_bot_out: '10人の人間営業を代替。眠らず、文句も言わず、成約のみに集中。',
      item_voice_setup: 'プライベート音声基盤構築',
      item_voice_setup_desc: '高並列VoIP/SIPサーバー展開。',
      item_voice_setup_feat: 'Asterisk/FreeSWITCH最適化、AIノイズ除去、世界ルート。',
      item_voice_setup_out: '完全自律型の通話ネットワークを所有。手数料ゼロ、データ主権確保。',
      item_video_remix: 'AI動画リミックスエンジン',
      item_video_remix_desc: '大量のオリジナルコンテンツ生成。',
      item_video_remix_feat: '重複排除、AI顔交換、自動字幕、シーンシャッフル。',
      item_video_remix_out: '毎日数千本の動画を生成し、TikTok/Reelsのアルゴリズムを支配。',
      item_risk_ctrl: '指紋対策コントロール',
      item_risk_ctrl_desc: 'アンチディテクトブラウザの中枢技術。',
      item_risk_ctrl_feat: 'Canvas/WebGLノイズ、フォント列挙隠蔽、音声指紋偽装。',
      item_risk_ctrl_out: '1台のマシンで数千のアカウントを運用しても関連性ゼロ。BAN連鎖を根絶。',
      item_competitor: '競合インテル・プローブ',
      item_competitor_desc: 'リアルタイムの市場スパイシステム。',
      item_competitor_feat: '広告ライブラリ収集、KW追跡、ファネル・リバースエンジニアリング。',
      item_competitor_out: '敵が動く前に戦略を察知し、次元の違う打撃を与える。',
      item_roi_dash: 'グローバルROIダッシュボード',
      item_roi_dash_desc: '集中型コマンドセンター。',
      item_roi_dash_feat: 'クロスプラットフォーム属性、LTVリアルタイム計算、コホート分析。',
      item_roi_dash_out: 'データ駆動の意思決定。帝国の鼓動を1つの画面で可視化。',
      item_rednote_matrix: 'RedNote (小紅書) マトリックス',
      item_rednote_matrix_desc: 'KOC種まき & AIインタラクション。',
      item_rednote_matrix_feat: 'アカウント育成自動化、コンテンツ生成、AIコメント介入。',
      item_rednote_matrix_out: '大量の素人アカウントで口コミを展開し、検索キーワードを独占。'
    },
    capabilities: {
      title: '全方位ビジネス体系',
      subtitle: '世界主要PFを網羅する9大作戦モジュール',
      learn_more: 'モジュール探索',
      modal_price: '価格問い合わせ',
      modal_content: 'コンテンツ最適化',
      modal_results: '効果測定',
      
      c1_title: '1. Telegram 帝国',
      c1_desc: '10万級のプライベートトラフィックプールを構築。収集、勧誘、一斉送信からMini App収益化まで。全自動育成で高信頼度を維持。',
      c1_tags: ['Mini App', '一斉送信', '収集', '自動応答', 'Chブースト', 'クローン群'],

      c2_title: '2. WhatsApp マトリックス',
      c2_desc: '公式APIとプロトコル版のハイブリッド。AI販売ボットが24時間体制で接客、追客、成約。到達率100%、BAN無視。',
      c2_tags: ['WS API', '一斉送信', 'AI接客', '一斉配信', '番号フィルタ', 'CRM同期'],

      c3_title: '3. TikTok 動画ストーム',
      c3_desc: 'AI動画核分裂エンジン。自動重複排除、顔交換、アフレコ。数千アカウントで一斉投稿し、おすすめフィードを制圧。',
      c3_tags: ['動画AI', '自動投稿', '無人ライブ', 'トレンド監視', 'AI顔交換', '行列コメント'],

      c4_title: '4. RedNote シーディング',
      c4_desc: 'KOCアカウントマトリックスと素人展開。AIによるコメント介入、検索KW独占。爆発的な「種まき」で高CVを実現。',
      c4_tags: ['KOC行列', 'AIコメント', 'SEO', '投稿生成', '順位保護', '素人展開'],

      c5_title: '5. Facebook 広告支配',
      c5_desc: 'FBアカウント育成と広告配信の自動化。BM高額アカウントのバッチ管理、自動予熱で実際のユーザー行動を模倣。',
      c5_tags: ['BM育成', 'Ads API', 'Pixel同期', 'ページ予熱', '自動異議', '競合スパイ'],

      c6_title: '6. グローバルクラウド基盤',
      c6_desc: '全てのビジネスの礎。純正Androidクラウド端末群 + 住宅IP。物理レベルの指紋隔離で、各アカウントに独立したIDを付与。',
      c6_tags: ['クラウド端末', '住宅IP', 'ADB制御', '指紋偽装', 'GPS位置', '自動SMS'],

      c7_title: '7. グローバル決済グリッド',
      c7_desc: '海外決済の壁を突破。無制限カード発行、越境送金、USDT匿名決済。高頻度取引のための金融インフラ。',
      c7_tags: ['仮想カード', '統合決済', '自動分配', '匿名決済', 'OTC取引', 'API決済'],

      c8_title: '8. グローバルSMS爆撃',
      c8_desc: '通信事業者直結ルート、到達率99%。Flash SMSによる強制ポップアップ対応。送信者ID変更で世界200カ国に精密着弾。',
      c8_tags: ['Flash SMS', '送信者ID', '大量送信', '認証回避', 'HLR洗浄', 'SIMファーム'],

      c9_title: '9. グローバル音声コマンド',
      c9_desc: 'VoIP回線の卸売りとAIコールセンター。番号通知偽装技術で応答率向上。AI音声ボットが見込み客を自動選別。',
      c9_tags: ['番号偽装', 'IVRナビ', 'SIPトランク', 'コールセンター', 'AI音声呼出', '匿名通話'],

      tag_details: {
        'Mini App': '高CV率のTelegram Mini App（Web3/TON互換）を開発。チャットから離脱させずに収益化。',
        '一斉送信': '高性能DMエンジン。ターゲットリストに対し毎日100万通以上のメッセージを送信可能。',
        '収集': '競合グループのメンバーデータを抽出（ID、アクティビティ、BioKW）し、精密にターゲティング。',
        '自動応答': 'KWベースのインテリジェントBot。見込み客とのエンゲージメントを24時間維持。',
        'Chブースト': '閲覧数とリアクションを自動注入。新規チャンネルの社会的証明を瞬時に構築。',
        'クローン群': '成功している競合グループの構造を複製し、コンテンツを注入してオーディエンスを奪う。',
        
        'WS API': 'Meta公式ビジネスAPI統合。グリーンバッジ、高到達率、BANリスクなし。',
        'AI接客': '微調整されたLLMエージェント。反論処理、通話予約、チャット内での成約を完遂。',
        '一斉配信': '変数テキストを使用したバルク送信。スパムフィルターを回避しリストにリーチ。',
        '番号フィルタ': '送信前に数百万の電話番号を即座にチェック。WhatsAppアクティブ状態を確認。',
        'CRM同期': 'HubSpot、Salesforce等とチャットログ・リードステータスをリアルタイム同期。',
        'ボタンMsg': 'クイックリプライとCTAボタン付きのインタラクティブメッセージ。クリック率300%向上。',

        '動画AI': 'ストック映像とAIナレーション、字幕をリミックスする自動動画生成エンジン。',
        '自動投稿': 'IP隔離を実現しながら、数千のTikTokアカウントでコンテンツを同時にスケジュール・公開。',
        '無人ライブ': 'ライブストリームに人工的なトラフィックとインタラクションを注入。アルゴリズム推奨をトリガー。',
        'トレンド監視': 'トレンドのハッシュタグと音源をリアルタイム監視。コンテンツ戦略を誘導。',
        'AI顔交換': 'AI駆動のディープフェイク技術。各マトリックスアカウントに独自のペルソナを作成。',
        '行列コメント': 'ボットアカウント群によるコメント欄の演出。バイラルな盛り上がりをシミュレート。',

        'KOC行列': '数千の「熟成」素人アカウントを使用し、KOC（Key Opinion Consumer）ネットワークを模倣。',
        'AIコメント': '競合投稿のコメントをスマートに傍受。興味を持った層を自社ブランドへ誘導。',
        'SEO': '投稿内容とエンゲージメントを最適化。特定の商品キーワードで検索結果を独占。',
        '投稿生成': 'RedNoteの美学に合わせて調整されたライフスタイル画像とコピーをAI生成。',
        '順位保護': '検索順位を維持し、悪意のあるネガティブコメントに対抗する防御メカニズム。',
        '素人展開': '「種まき（Zhongcao）」コンテンツを大量投下。「ネット全体で推奨」という世論を形成。',

        'BM育成': 'ビジネスネージャーを自動的に予熱（Warmup）。支出制限と信頼スコアを向上。',
        'Ads API': 'プログラムによる広告セットの作成とA/Bテスト。大規模運用を自動化。',
        'Pixel同期': 'サーバーサイド追跡により、iOS 14以降のプライバシー制限を回避。失われた属性データを回復。',
        'ページ予熱': 'ファンページでの自動投稿と交流。アクティブな実ビジネスの振る舞いを模倣。',
        '自動異議': '制限されたアカウントに対し、AI駆動で異議申し立てフォームを送信。高い成功率を維持。',
        '競合スパイ': '競合他社の広告をリバースエンジニアリング。勝てるクリエイティブと戦略を暴く。',

        'クラウド端末': 'データセンターでホストされる本物のSnapdragon搭載Android端末。Web経由でアクセス。',
        '住宅IP': 'AT&T/Verizon等の静的住宅用IP。トラフィックを100%人間・現地からのものに見せる。',
        'ADB制御': 'Android Debug Bridgeへの直接アクセス。画面上のあらゆる操作をプログラム制御。',
        '指紋偽装': 'ハードウェアレベルのなりすまし（IMEI、MAC、Canvas）。アカウントの紐付けを防止。',
        'GPS位置': '正確な地理位置情報を注入。特定の都市や地域のユーザーをシミュレート。',
        '自動SMS': 'SMS認証コードを自動抽出し、シームレスなアカウント登録を実現。',

        '仮想カード': '広告費（FB/Google）や報酬支払いに使える無制限のVisa/Mastercard仮想カード即時発行。',
        '統合決済': 'クレカ、電子マネー、ローカル決済など世界中の主要決済を統合。決済成功率を向上。',
        '自動分配': 'スマートコントラクトやAPIに基づく自動分配。収益を代理店やパートナーに即時配分。',
        '匿名決済': 'USDT/USDCなどの暗号資産決済に対応。取引のプライバシー保護と為替規制回避。',
        'OTC取引': '大口の相対取引デスク。競争力のあるレートで、資金を安全かつ迅速に着金させる。',
        'API決済': '開発者向け決済IF。あらゆるアプリやWebに簡単に統合、コールバック通知対応。',

        'Flash SMS': 'Class 0レベルのSMS。受信者の画面にポップアップ表示させ、強制的に読ませる（読後消滅）。',
        '送信者ID': 'SMSの送信者ID（Sender ID）を変更可能。ブランド信頼性を向上（現地規制準拠要）。',
        '大量送信': '高並列SMSゲートウェイ。1時間あたり数百万件のマーケティングSMSを即時到達させる。',
        '認証回避': 'SMS受信プラットフォームへの接続。世界中の人気アプリの認証コード受信をサポート。',
        'HLR洗浄': '送信前に番号の状態（空き番、停止、ローミング）を検出。コスト削減とCV率向上。',
        'SIMファーム': '物理SIMカードプールに基づく送信ソリューション。キャリアのブロック戦略を回避。',

        '番号偽装': '発信者番号表示（CLI）の変更に対応。電話の応答率を上げ、現地での信頼を確立。',
        'IVRナビ': 'インテリジェント音声ナビ。顧客のキー操作を誘導し、見込み客を自動選別。',
        'SIPトランク': '高品質なVoIP回線の卸売り。国際通話を極めて低いレートで提供。クリアで安定。',
        'コールセンター': 'クラウド型コールセンター。プレディクティブダイヤル、監視、録音品質チェック。',
        'AI音声呼出': '人間のようなAI音声ロボットが大規模アウトバウンドを実施。顧客意向を識別しタグ付け。',
        '匿名通話': '中間番号技術で通話双方のプライバシーを保護。配車やデリバリー等の用途に。'
      }
    }
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // 默认语言改为中文
  const [language, setLanguage] = useState<Language>('cn');

  const t = (key: string) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        // Fallback to English
        let fallback = translations['en'];
        for (const fk of keys) {
            if (fallback && typeof fallback === 'object' && fk in fallback) {
                fallback = fallback[fk];
            } else {
                return key;
            }
        }
        return fallback || key;
      }
    }
    return value;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};